In [2]:
import numpy as np
a= np.array ([1,2,3,4])
print ("one dimensionanl array :",a)


one dimensionanl array : [1 2 3 4]


In [3]:
import numpy as np
b= np.array([[1,2,3,4],[5,6,8,9]])
print ("two dimensionanl array:",b)


two dimensionanl array: [[1 2 3 4]
 [5 6 8 9]]


In [8]:
import numpy as np
c=np.zeros((3,5))
print ("\n arry with all zeros:\n",c)



 arry with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
d=np.random.random ((3,2))
print ("\n Random value:\n",d)




 Random value:
 [[0.99421048 0.91144797]
 [0.5321095  0.33465468]
 [0.13157011 0.27497782]]


In [5]:
import numpy as np
d=np.arange(0,5,2)
print ("\n Range value:\n",d)




 Range value:
 [0 2 4]


In [1]:
import numpy as np
array=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
newarr=array.reshape((4,3))
print("\n orginal array \n",array)
print("\n reshape array\n",newarr)






 orginal array 
 [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

 reshape array
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]


In [6]:
import numpy as np 
x=np.array([[1,2,3],[5,6,7],[9,0,1],[1,2,3],[3,4,9]])
print(x)
a=np.zeros((5,3))
print("\n Array with all zeros:\n",a)
b=np.random.random((5,3))
print("\n random value:\n",b)
c=np.arange(0,30,5)
print("\n Range value\n",c)
u=x.reshape((3,5))
print("\n reshape array",u)

[[1 2 3]
 [5 6 7]
 [9 0 1]
 [1 2 3]
 [3 4 9]]

 Array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 random value:
 [[0.26319965 0.05086972 0.90755831]
 [0.48797779 0.80440913 0.02383795]
 [0.7265713  0.98693144 0.93539563]
 [0.72568449 0.58985329 0.99406195]
 [0.59899662 0.99427082 0.36778043]]

 Range value
 [ 0  5 10 15 20 25]

 reshape array [[1 2 3 5 6]
 [7 9 0 1 1]
 [2 3 3 4 9]]


In [7]:
import numpy as np
flat=x.flatten()
print("flatten array:",flat)

flatten array: [1 2 3 5 6 7 9 0 1 1 2 3 3 4 9]


In [14]:
 print("The number of dimasionan",x.ndim)

The number of dimasionan 2


In [15]:
print("\n shape array",u.shape)


 shape array (3, 5)


In [6]:
import numpy as np
x= np.array([[1,2,3],[4,5,6]])
print("\array element type:",x.dtype)

rray element type: int32


In [7]:
import numpy as np
x= np.array([[1,2,3],[4,5,6]])
size=len(x)
print("size: ",size)

size:  2
