In [3]:
#index Retrieval
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==2)
print(x)

(array([2], dtype=int64),)


In [7]:
#index of the input element

import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [8]:
#sorting
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))
a=np.array([[7,4,9],[9,1,4]])
print(np.sort(a))

[2 4 5 6 7 9]
[[4 7 9]
 [1 4 9]]


In [9]:
#booolean indexing
import numpy as np
arr=np.array([31,78,69,88])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[78 88]


In [12]:
#boolean indexing using condition
import numpy as np
arr=np.array([31,78,69,88])
filter_arr=arr<70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False  True False]
[31 69]
