In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
slice=arr[2:6]
print(slice)


[3 4 5 6]


In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
slice=arr[::2]
print(slice)

[1 3 5 7]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
slice=arr[::-1]
print(slice)


[7 6 5 4 3 2 1]


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[8,9,0]])
slice=arr[0:2,1:3]
print(slice)


[[2 3]
 [5 6]]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[8,9,0]])
c=arr[:,0]
r=arr[2,]
print(c)
print(r)


[1 4 8]
[8 9 0]


In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[8,9,0]])
print(arr[0,0])
print(arr[1,2])


1
6


In [14]:
import numpy as np
arr=np.array([1,2,3])
print(arr[1])


2


In [19]:
import numpy as np
arr=np.array([1,2,3])
print(arr[-2])

2


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [22]:
import numpy as np
arr=np.array([1,2,3])
print(arr[arr>2])

[3]


In [25]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [26]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [31]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7])
q=np.array_split(arr1,2)
print(q)


[array([1, 2, 3, 4]), array([5, 6, 7])]
